"""add study_year to member

Revision ID: 214b765b9913
Revises: 5e7c04e44f05
Create Date: 2026-02-15 11:45:31.226254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214b765b9913'
down_revision: Union[str, Sequence[str], None] = '5e7c04e44f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('study_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'study_year')
    # ### end Alembic commands ###
