"""test autogenerate

Revision ID: 5e7c04e44f05
Revises: e455f709681f
Create Date: 2026-02-15 11:38:44.888084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7c04e44f05'
down_revision: Union[str, Sequence[str], None] = 'e455f709681f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_program',
    sa.Column('academic_program_id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('academic_program_id'),
    sa.UniqueConstraint('program_name')
    )
    op.create_table('permission',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('project',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'finished', 'archived', name='project_status'), server_default='planned', nullable=False),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.CheckConstraint('finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at', name='project_finish_after_start'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('social_platform_snapshot',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=60), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.CheckConstraint('comments IS NULL OR comments >= 0', name='comments_non_negative'),
    sa.CheckConstraint('followers >= 0', name='followers_non_negative'),
    sa.CheckConstraint('likes IS NULL OR likes >= 0', name='likes_non_negative'),
    sa.CheckConstraint('reach IS NULL OR reach >= 0', name='reach_non_negative'),
    sa.CheckConstraint('shares IS NULL OR shares >= 0', name='shares_non_negative'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('platform', 'snapshot_date', name='ux_social_platform_snapshot')
    )
    op.create_table('sponsor',
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_company', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('contact_person_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sponsor_id')
    )
    op.create_table('member',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('academic_program_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_program_id'], ['academic_program.academic_program_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('activity_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('speaker_name', sa.String(length=200), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('created_by_member_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_datetime IS NULL OR end_datetime >= start_datetime', name='event_end_after_start'),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['member.member_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('member_role',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'role_id')
    )
    op.create_table('project_member',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('project_role', sa.String(length=60), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('left_at IS NULL OR left_at >= joined_at', name='left_after_joined'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'member_id')
    )
    op.create_table('academic_credit',
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('credits_amount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('(project_id IS NOT NULL AND event_id IS NULL) OR (project_id IS NULL AND event_id IS NOT NULL)', name='academic_credit_exactly_one_target'),
    sa.CheckConstraint('credits_amount > 0', name='credits_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('credit_id')
    )
    op.create_table('event_application',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decision_status', sa.Enum('pending', 'accepted', 'rejected', 'waitlisted', 'cancelled', name='decision_status'), server_default='pending', nullable=False),
    sa.Column('attendance_status', sa.Enum('unknown', 'attended', 'no_show', name='attendance_status'), server_default='unknown', nullable=False),
    sa.Column('attendance_mode', sa.Enum('in_person', 'online', name='attendance_mode'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'member_id')
    )
    op.create_table('event_feedback',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='rating_1_to_5'),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index('ux_event_feedback_one_per_member', 'event_feedback', ['event_id', 'member_id'], unique=True, postgresql_where=sa.text('member_id IS NOT NULL'))
    op.create_table('event_sponsor',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('money_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('money_currency', sa.String(length=3), nullable=True),
    sa.Column('in_kind_description', sa.Text(), nullable=True),
    sa.Column('in_kind_estimated_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('in_kind_estimated_value IS NULL OR in_kind_estimated_value >= 0', name='in_kind_value_non_negative'),
    sa.CheckConstraint('money_amount IS NOT NULL OR in_kind_description IS NOT NULL OR in_kind_estimated_value IS NOT NULL', name='sponsor_contribution_present'),
    sa.CheckConstraint('money_amount IS NULL OR money_amount >= 0', name='money_amount_non_negative'),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsor.sponsor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'sponsor_id')
    )
    op.create_table('finance_transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('income', 'expense', name='finance_transaction_type'), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_by_member_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('amount_cents > 0', name='amount_cents_positive'),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['member.member_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.drop_table('members')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('members_pkey')),
    sa.UniqueConstraint('email', name=op.f('members_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('finance_transaction')
    op.drop_table('event_sponsor')
    op.drop_index('ux_event_feedback_one_per_member', table_name='event_feedback', postgresql_where=sa.text('member_id IS NOT NULL'))
    op.drop_table('event_feedback')
    op.drop_table('event_application')
    op.drop_table('academic_credit')
    op.drop_table('project_member')
    op.drop_table('member_role')
    op.drop_table('event')
    op.drop_table('activity_log')
    op.drop_table('role_permission')
    op.drop_table('member')
    op.drop_table('sponsor')
    op.drop_table('social_platform_snapshot')
    op.drop_table('role')
    op.drop_table('project')
    op.drop_table('permission')
    op.drop_table('academic_program')
    # ### end Alembic commands ###
