"""add project applications

Revision ID: 841d2214e6ca
Revises: 94abda19daf2
Create Date: 2026-03-18 22:03:19.703242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841d2214e6ca'
down_revision: Union[str, Sequence[str], None] = '94abda19daf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_application',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('desired_role', sa.String(length=60), nullable=False),
    sa.Column('application_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'withdrawn', name='project_application_status'), server_default='pending', nullable=False),
    sa.Column('manager_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_member_id'], ['member.member_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('project_id', 'member_id', 'status', name='uq_project_application_project_member_status')
    )
    op.create_index('ix_project_application_member_id', 'project_application', ['member_id'], unique=False)
    op.create_index('ix_project_application_project_id', 'project_application', ['project_id'], unique=False)
    op.create_index('ix_project_application_status', 'project_application', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_application_status', table_name='project_application')
    op.drop_index('ix_project_application_project_id', table_name='project_application')
    op.drop_index('ix_project_application_member_id', table_name='project_application')
    op.drop_table('project_application')
    # ### end Alembic commands ###
