"""remove event_feedback

Revision ID: 94abda19daf2
Revises: bc20f9129a9c
Create Date: 2026-03-05 08:48:04.199464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94abda19daf2'
down_revision: Union[str, Sequence[str], None] = 'bc20f9129a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ux_event_feedback_one_per_member'), table_name='event_feedback', postgresql_where='(member_id IS NOT NULL)')
    op.drop_table('event_feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_feedback',
    sa.Column('feedback_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('rating_1_to_5')),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], name=op.f('event_feedback_event_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], name=op.f('event_feedback_member_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('feedback_id', name=op.f('event_feedback_pkey'))
    )
    op.create_index(op.f('ux_event_feedback_one_per_member'), 'event_feedback', ['event_id', 'member_id'], unique=True, postgresql_where='(member_id IS NOT NULL)')
    # ### end Alembic commands ###
