"""embed feedback into event_application

Revision ID: bc20f9129a9c
Revises: 6a0981a0e75c
Create Date: 2026-02-27 16:44:18.425561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc20f9129a9c'
down_revision: Union[str, Sequence[str], None] = '6a0981a0e75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_application', sa.Column('feedback_rating', sa.Integer(), nullable=True))
    op.add_column('event_application', sa.Column('feedback_comment', sa.Text(), nullable=True))
    op.add_column('event_application', sa.Column('feedback_submitted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_application', 'feedback_submitted_at')
    op.drop_column('event_application', 'feedback_comment')
    op.drop_column('event_application', 'feedback_rating')
    # ### end Alembic commands ###
