"""add member_auth and auth_session

Revision ID: ee7a6382dd05
Revises: 214b765b9913
Create Date: 2026-02-24 16:08:59.648455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7a6382dd05'
down_revision: Union[str, Sequence[str], None] = '214b765b9913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_session',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_label', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_auth_session_expires_at'), 'auth_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_session_member_id'), 'auth_session', ['member_id'], unique=False)
    op.create_index(op.f('ix_auth_session_revoked_at'), 'auth_session', ['revoked_at'], unique=False)
    op.create_table('member_auth',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('password_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_auth')
    op.drop_index(op.f('ix_auth_session_revoked_at'), table_name='auth_session')
    op.drop_index(op.f('ix_auth_session_member_id'), table_name='auth_session')
    op.drop_index(op.f('ix_auth_session_expires_at'), table_name='auth_session')
    op.drop_table('auth_session')
    # ### end Alembic commands ###
